name: Debug Workflow

on:
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/wave/**'
      - 'packages/types/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'turbo.json'

jobs:
  debug:
    name: Debug Info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Debug
        run: |
          echo "PR Target Branch: ${{ github.base_ref }}"
          echo "PR Source Branch: ${{ github.head_ref }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Workflow triggered successfully!"
